require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TranslantionsController do

  # This should return the minimal set of attributes required to create a valid
  # Translantion. As you add validations to Translantion, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "original" => "MyText" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TranslantionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all translantions as @translantions" do
      translantion = Translantion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:translantions).should eq([translantion])
    end
  end

  describe "GET show" do
    it "assigns the requested translantion as @translantion" do
      translantion = Translantion.create! valid_attributes
      get :show, {:id => translantion.to_param}, valid_session
      assigns(:translantion).should eq(translantion)
    end
  end

  describe "GET new" do
    it "assigns a new translantion as @translantion" do
      get :new, {}, valid_session
      assigns(:translantion).should be_a_new(Translantion)
    end
  end

  describe "GET edit" do
    it "assigns the requested translantion as @translantion" do
      translantion = Translantion.create! valid_attributes
      get :edit, {:id => translantion.to_param}, valid_session
      assigns(:translantion).should eq(translantion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Translantion" do
        expect {
          post :create, {:translantion => valid_attributes}, valid_session
        }.to change(Translantion, :count).by(1)
      end

      it "assigns a newly created translantion as @translantion" do
        post :create, {:translantion => valid_attributes}, valid_session
        assigns(:translantion).should be_a(Translantion)
        assigns(:translantion).should be_persisted
      end

      it "redirects to the created translantion" do
        post :create, {:translantion => valid_attributes}, valid_session
        response.should redirect_to(Translantion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved translantion as @translantion" do
        # Trigger the behavior that occurs when invalid params are submitted
        Translantion.any_instance.stub(:save).and_return(false)
        post :create, {:translantion => { "original" => "invalid value" }}, valid_session
        assigns(:translantion).should be_a_new(Translantion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Translantion.any_instance.stub(:save).and_return(false)
        post :create, {:translantion => { "original" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested translantion" do
        translantion = Translantion.create! valid_attributes
        # Assuming there are no other translantions in the database, this
        # specifies that the Translantion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Translantion.any_instance.should_receive(:update_attributes).with({ "original" => "MyText" })
        put :update, {:id => translantion.to_param, :translantion => { "original" => "MyText" }}, valid_session
      end

      it "assigns the requested translantion as @translantion" do
        translantion = Translantion.create! valid_attributes
        put :update, {:id => translantion.to_param, :translantion => valid_attributes}, valid_session
        assigns(:translantion).should eq(translantion)
      end

      it "redirects to the translantion" do
        translantion = Translantion.create! valid_attributes
        put :update, {:id => translantion.to_param, :translantion => valid_attributes}, valid_session
        response.should redirect_to(translantion)
      end
    end

    describe "with invalid params" do
      it "assigns the translantion as @translantion" do
        translantion = Translantion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Translantion.any_instance.stub(:save).and_return(false)
        put :update, {:id => translantion.to_param, :translantion => { "original" => "invalid value" }}, valid_session
        assigns(:translantion).should eq(translantion)
      end

      it "re-renders the 'edit' template" do
        translantion = Translantion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Translantion.any_instance.stub(:save).and_return(false)
        put :update, {:id => translantion.to_param, :translantion => { "original" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested translantion" do
      translantion = Translantion.create! valid_attributes
      expect {
        delete :destroy, {:id => translantion.to_param}, valid_session
      }.to change(Translantion, :count).by(-1)
    end

    it "redirects to the translantions list" do
      translantion = Translantion.create! valid_attributes
      delete :destroy, {:id => translantion.to_param}, valid_session
      response.should redirect_to(translantions_url)
    end
  end

end
